// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_thermometer_png);    // assets/thermometer.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/humidity.png
LV_IMG_DECLARE(ui_img_lightbulb_png);    // assets/lightbulb.png
LV_IMG_DECLARE(ui_img_diode_png);    // assets/diode.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
